# Generated by Django 5.2.3 on 2025-06-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_fix_gestor_str'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gestorcliente',
            options={},
        ),
    ]
