# Generated by Django 5.2.3 on 2025-06-24 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nombre del Cliente"
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="RUT del Cliente"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="Dirección"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="CentroCosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del Centro de Costo"
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=20, verbose_name="Código del Centro de Costo"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="centros_costo",
                        to="flota_app.cliente",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Costo",
                "verbose_name_plural": "Centros de Costo",
                "unique_together": {("codigo", "cliente")},
            },
        ),
        migrations.CreateModel(
            name="Instalacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Instalación"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="Dirección"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "centro_costo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instalaciones",
                        to="flota_app.centrocosto",
                        verbose_name="Centro de Costo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instalación",
                "verbose_name_plural": "Instalaciones",
                "unique_together": {("nombre", "centro_costo")},
            },
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "rut",
                    models.CharField(max_length=12, unique=True, verbose_name="RUT"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de Nacimiento"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=200, verbose_name="Dirección"),
                ),
                (
                    "telefono_contacto",
                    models.CharField(
                        max_length=15, verbose_name="Teléfono de Contacto"
                    ),
                ),
                (
                    "acepta_mensajeria_whatsapp",
                    models.BooleanField(
                        default=False, verbose_name="Acepta Mensajería WhatsApp"
                    ),
                ),
                (
                    "legajo",
                    models.CharField(max_length=20, unique=True, verbose_name="Legajo"),
                ),
                ("fecha_ingreso", models.DateField(verbose_name="Fecha de Ingreso")),
                (
                    "centro_costo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_asociado",
                        to="flota_app.centrocosto",
                        verbose_name="Centro de Costo",
                    ),
                ),
                (
                    "instalacion_trabajo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_asignado",
                        to="flota_app.instalacion",
                        verbose_name="Instalación de Trabajo",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Personal",
                "verbose_name_plural": "Personal",
            },
        ),
        migrations.CreateModel(
            name="AsignacionInstalacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_inicio_asignacion",
                    models.DateField(verbose_name="Fecha de Inicio de Asignación"),
                ),
                (
                    "fecha_fin_asignacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Fin de Asignación"
                    ),
                ),
                (
                    "instalacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_asignado_historial",
                        to="flota_app.instalacion",
                        verbose_name="Instalación",
                    ),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_instalacion",
                        to="flota_app.personal",
                        verbose_name="Personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Instalación",
                "verbose_name_plural": "Asignaciones de Instalaciones",
                "ordering": ["-fecha_inicio_asignacion"],
            },
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_turno",
                    models.CharField(
                        choices=[
                            ("D", "Día (07:00 - 19:00)"),
                            ("N", "Noche (19:00 - 07:00)"),
                            ("E", "Extra"),
                        ],
                        max_length=1,
                        verbose_name="Tipo de Turno",
                    ),
                ),
                (
                    "fecha_hora_inicio",
                    models.DateTimeField(verbose_name="Fecha y Hora de Inicio"),
                ),
                (
                    "fecha_hora_fin",
                    models.DateTimeField(verbose_name="Fecha y Hora de Fin"),
                ),
                (
                    "instalacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turnos_asignados",
                        to="flota_app.instalacion",
                        verbose_name="Instalación Asignada",
                    ),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnos",
                        to="flota_app.personal",
                        verbose_name="Personal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno",
                "verbose_name_plural": "Turnos",
                "ordering": ["fecha_hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patente",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Patente"
                    ),
                ),
                ("marca", models.CharField(max_length=50, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=50, verbose_name="Modelo")),
                ("año", models.IntegerField(verbose_name="Año")),
                ("kilometraje", models.IntegerField(verbose_name="Kilometraje")),
                (
                    "en_reparacion",
                    models.BooleanField(default=False, verbose_name="En Reparación"),
                ),
                (
                    "instalacion_base",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehiculos_asociados",
                        to="flota_app.instalacion",
                        verbose_name="Instalación Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
            },
        ),
        migrations.CreateModel(
            name="GestionTransporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_viaje",
                    models.CharField(
                        choices=[
                            ("I", "Ida (Casa -> Trabajo)"),
                            ("V", "Vuelta (Trabajo -> Casa)"),
                        ],
                        max_length=1,
                        verbose_name="Tipo de Viaje",
                    ),
                ),
                (
                    "fecha_hora_programada",
                    models.DateTimeField(verbose_name="Fecha y Hora Programada"),
                ),
                (
                    "direccion_origen",
                    models.CharField(max_length=200, verbose_name="Dirección Origen"),
                ),
                (
                    "direccion_destino",
                    models.CharField(max_length=200, verbose_name="Dirección Destino"),
                ),
                (
                    "confirmado",
                    models.BooleanField(default=False, verbose_name="Viaje Confirmado"),
                ),
                (
                    "realizado",
                    models.BooleanField(default=False, verbose_name="Viaje Realizado"),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viajes_transporte",
                        to="flota_app.personal",
                        verbose_name="Personal",
                    ),
                ),
                (
                    "turno_asociado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transporte_asociado",
                        to="flota_app.turno",
                        verbose_name="Turno Asociado",
                    ),
                ),
                (
                    "vehiculo_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transportes_realizados",
                        to="flota_app.vehiculo",
                        verbose_name="Vehículo Asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gestión de Transporte",
                "verbose_name_plural": "Gestiones de Transporte",
                "ordering": ["-fecha_hora_programada"],
            },
        ),
        migrations.CreateModel(
            name="AsignacionVehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Asignación"
                    ),
                ),
                (
                    "fecha_devolucion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Devolución"
                    ),
                ),
                (
                    "personal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones_vehiculo",
                        to="flota_app.personal",
                        verbose_name="Personal",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="flota_app.vehiculo",
                        verbose_name="Vehículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Vehículo",
                "verbose_name_plural": "Asignaciones de Vehículos",
                "ordering": ["-fecha_asignacion"],
            },
        ),
    ]
