# Generated by Django 5.2.3 on 2025-06-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flota_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instalacion",
            name="latitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitud"),
        ),
        migrations.AddField(
            model_name="instalacion",
            name="longitud",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitud"),
        ),
    ]
